<div id="emoji-picker-container"
    class="fixed top-20 right-6 z-[9999] hidden animate-in fade-in slide-in-from-top-4 duration-300">
    <div class="glass-card !p-0 w-80 shadow-2xl border-white/10 overflow-hidden">
        <!-- Header / Search -->
        <div class="p-4 border-b border-white/5 bg-white/5">
            <div class="flex items-center justify-between mb-4">
                <h3
                    class="text-[10px] font-black text-p-title uppercase tracking-widest italic flex items-center gap-2">
                    <span class="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
                    Emoji Universe
                </h3>
                <button onclick="toggleEmojiPicker()" class="text-p-muted hover:text-white transition-colors">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12">
                        </path>
                    </svg>
                </button>
            </div>
            <div class="relative">
                <input type="text" id="emoji-search" placeholder="Buscar emoji..."
                    class="form-input !py-2 !px-8 text-xs !bg-black/20" oninput="filterEmojis(this.value)">
                <svg class="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-p-muted" fill="none"
                    stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </div>
        </div>

        <!-- Categories Nav -->
        <div class="flex items-center gap-1 p-2 bg-black/20 border-b border-white/5 overflow-x-auto no-scrollbar">
            <button onclick="scrollToEmojiCategory('faces')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all" title="Caras">😀</button>
            <button onclick="scrollToEmojiCategory('nature')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all"
                title="Naturaleza">🌿</button>
            <button onclick="scrollToEmojiCategory('food')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all" title="Comida">🍎</button>
            <button onclick="scrollToEmojiCategory('activities')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all"
                title="Actividades">⚽</button>
            <button onclick="scrollToEmojiCategory('travel')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all" title="Viajes">✈️</button>
            <button onclick="scrollToEmojiCategory('objects')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all" title="Objetos">💡</button>
            <button onclick="scrollToEmojiCategory('symbols')"
                class="emoji-cat-btn p-2 hover:bg-white/5 rounded-lg text-lg transition-all"
                title="Símbolos">❤️</button>
        </div>

        <!-- Emoji Grid -->
        <div id="emoji-grid" class="h-64 overflow-y-auto p-4 grid grid-cols-6 gap-2 custom-scrollbar scroll-smooth">
            <!-- Content generated by JS -->
        </div>

        <!-- Preview Footer -->
        <div id="emoji-preview"
            class="p-3 bg-white/5 border-t border-white/5 flex items-center gap-3 text-p-muted italic text-[10px]">
            Selecciona un emoji para insertar
        </div>
    </div>
</div>

<script>
    const EMOJI_DATA = {
        faces: { label: 'Caras', emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇', '🙂', '🙃', '😉', '😌', '😍', '🥰', '😘', '😗', '😙', '😚', '😋', '😛', '😝', '😜', '🤪', '🤨', '🧐', '🤓', '😎', '🤩', '🥳', '😏', '😒', '😞', '😔', '😟', '😕', '🙁', '☹️', '😣', '😖', '😫', '😩', '🥺', '😢', '😭', '😤', '😠', '😡', '🤬', '🤯', '😳', '🥵', '🥶', '😱', '😨', '😰', '😥', '😓', '🤗', '🤔', '🤭', '🤫', '🤥', '😶', '😐', '😑', '😬', '🙄', '😯', '😦', '😧', '😮', '😲', '🥱', '😴', '🤤', '😪', '😵', '🤐', '🥴', '🤢', '🤮', '🤧', '🥵', '🥶'] },
        nature: { label: 'Naturaleza', emojis: ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐻‍❄️', '🐨', '🐯', '🦁', '🐮', '🐷', '🐽', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗', '🐴', '🦄', '🐝', '🐛', '🦋', '🐌', '🐞', '🐜', '🦟', '🦗', '🕷', '🕸', '🦂', '🐢', '🐍', '🦎', '🦖', '🦕', '🐙', '🦑', '🦐', '🦞', '🦀', '🐡', '🐠', '🐟', '🐬', '🐳', '🐋', '🦈', '🐊', '🐅', '🐆', '🦓', '🦍', '🦧', '🐘', '🦛', '🦏', '🐪', '🐫', '🦒', '🦘', '🦬', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑', '🐐', '🦌', '🐕', '🐩', '🦮', '🐕‍🦺', '🐈', '🐈‍⬛', '🐓', '🦃', '🦚', '🦜', '🦢', '🦩', '🕊', '🐇', '🦝', '🦨', '🦡', '🦫', '🦦', '🦥', '🐁', '🐀', '🐿', '🦔', '🌵', '🎄', '🌲', '🌳', '🌴', '🌱', '🌿', '☘️', '🍀', '🎍', '🎋', '🍃', '🍂', '🍁', '🍄', '🌾', '💐', '🌷', '🌹', '🥀', '🌺', '🌸', '🌼', '🌻', '🌞', '🌝', '🌛', '🌜', '🌚', '🌕', '🌖', '🌗', '🌘', '🌑', '🌒', '🌓', '🌔', '🌙', '🌎', '🌍', '🌏', '🪐', '💫', '⭐️', '🌟', '✨', '⚡️', '☄️', '💥', '🔥', '🌪', '🌈', '☀️', '🌤', '⛅️', '🌥', '☁️', '🌦', '🌧', '⛈', '🌩', '🌨', '❄️', '☃️', '⛄️', '🌬', '💨', '💧', '💦', '☔️'] },
        food: { label: 'Comida', emojis: ['🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', ' melon', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅', '🍆', '🥑', '🥦', '🥬', '🥒', '🌶', '😾', '🌽', '🥕', '🫒', '🧄', '🧅', '🥔', '🍠', '🥐', '🥯', '🍞', '🥖', '🥨', '🧀', '🥚', '🍳', '🧈', '🥞', '🧇', '🥓', '🥩', '🍗', '🍖', '🦴', '🌭', '🍔', '🍟', '🍕', '🫓', '🥪', '🥙', '🧆', '🌮', '🌯', '🥗', '🥘', '🫕', '🥣', '🍝', '🍜', '🍲', '🍛', '🍣', '🍱', '🥟', '🦪', '🍤', '🍙', '🍚', '🍘', '🍥', '🥠', '🥮', '🍢', '🍡', '🍧', '🍨', '🍦', '🥧', '🧁', '🍰', '🎂', '🍮', '🍭', '🍬', '🍫', '🍿', '🍩', '🍪', '🌰', '🥜', '🍯', '🥛', '☕️', '🫖', '🍵', '🍶', '🍺', '🍻', '🥂', '🍷', '🥃', '🍸', '🍹', '🧉', '🍾', '🧊', '🥤', '🧋'] },
        activities: { label: 'Actividades', emojis: ['⚽️', '🏀', '🏈', '⚾️', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳️', '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛼', '🛷', '⛸', '🥌', '🎿', '⛷', '🏂', '🏋️‍♀️', '🤼‍♂️', '🤸‍♀️', '⛹️‍♂️', '🤺', '🤾‍♂️', '🏌️‍♂️', '🏇', '🧘‍♀️', '🏄‍♂️', '🏊‍♂️', '🤽‍♂️', '🚣‍♂️', '🧗‍♂️', '🚵‍♂️', '🚴‍♂️', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖', '🏵', '🎫', '🎟', '🎭', '🎨', '🖼', '🧵', '🪡', '🧶', '🎸', '🎻', '🎷', '🎺', '🎸', '🥁', '🪘'] },
        travel: { label: 'Viajes', emojis: ['🚗', '🚕', '🚙', '🚌', '🚎', '🏎', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🏍', '🛵', '🦽', '🦼', '🛺', '🚲', '🛹', '🛴', '⚓️', '⛵️', '🛶', '🚤', '🛳', '⛴', '🚢', '✈️', '🛩', '🛫', '🛬', '🪂', '💺', '🚁', '🚟', '🚠', '🚡', '🛰', '🚀', '🛸', '🛸', '🛎', '🧳', '⌛️', '⏳', '⌚️', '⏰', '⏱', '⏲', '🕰', '🌡', '☀️', '🌤', '⛅️', '🌥', '☁️', '🌦', '🌧', '⛈', '🌩', '🌨', '❄️', '☃️', '⛄️'] },
        objects: { label: 'Objetos', emojis: ['⌚️', '📱', '📲', '💻', '⌨️', '🖱', '🖨', '🖥', '🖱', '🖲', '🕹', '🗜', '💽', '💾', '💿', '📀', '📼', '📷', '📸', '📹', '🎥', '📽', '🎞', '📞', '☎️', '📟', '📠', '📺', '📻', '🎙', '🎚', '🎛', '🧭', '⏱', '⏲', '⏰', '🕰', '⌛️', '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯', '🪔', '🧯', '🛢', '💸', '💵', '💴', '💶', '💷', '🪙', '💰', '💳', '💎', '⚖️', '🪜', '🧰', '🪛', '🔧', '🔨', '⚒', '🛠', '⛏', '🪚', '🔫', '💣', '🧨', '🪓', '🔪', '🗡', '⚔️', '🛡', '🚬', '⚰️', '🪦', '⚱️', '🏺', '🔮', '📿', '🧿', '💈', '⚗️', '🔭', '🔬', '🕳', '🩹', '🩺', '💊', '💉', '🩸', '🧬', '🦠', '🧫', '🧪', '🌡', '🧹', '🧺', '🧻', '🚽', '🚰', '🚿', '🛁', '🛀', '🧼', '🪥', '🪒', '🧽', '🪣', '🧴', '🛎', '🔑', '🗝', '🚪', '🪑', '🛋', '🛌', '🛏', '🧸', '🪆', '🖼', '🪞', '🧺', '🧹', '🧹', '🧴'] },
        symbols: { label: 'Símbolos', emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮️', '✝️', '☪️', '🕉', '☸️', '✡️', '🔯', '🕎', '☯️', '☦️', '🛐', '⛎', '♈️', '♉️', '♊️', '♋️', '♌️', '♍️', '♎️', '♏️', '♐️', '♑️', '♒️', '♓️', '🆔', '⚛️', '🉑', '☢️', '☣️', '📴', '📳', '🈶', '🈚️', '🈸', '🈺', '🈷️', '✴️', '🆚', '💮', '🉐', '㊙️', '㊗️', '🈴', '🈵', '🈹', '🈲', '🅰️', '🅱️', '🆎', '🆑', '🅾️', '🆘', '❌', '⭕️', '🛑', '⛔️', '📛', '🚫', '💯', '💢', '♨️', '🚷', '🚯', '🚳', '🚱', '🔞', '📵', '🚭', '❗', '❕', '❓', '❔', '‼️', '⁉️', '🔅', '🔆', '〽️', '⚠️', '🚸', '🔰', '♻️', '🈯️', '💹', '❇️', '✳️', '❎', '✅', '💠', '🌀', '➿', '🌐', 'Ⓜ️', '🏧', '🈂️', '🛂', '🛃', '🛄', '🛅', '♿️', '🚭', '🚾', '🅿️', '🚰', '🚹', '🚺', '🚼', '🚻', '🚮', '🎦', '📶', '🈁', '🔣', 'ℹ️', '🔤', '🔡', '🔠', '🆖', '🆗', '🆙', '🆒', '🆕', '🆓', '0️', '1️', '2️', '3️', '4️', '5️', '6️', '7️', '8️', '9️', '🔟', '🔢', '#️', '*️', '⏏️', '▶️', '⏸', '⏯', '⏹', '⏺', '⏭', '⏮', '⏩', '⏪', '⏫', '⏬', '◀️', '🔼', '🔽', '➡️', '⬅️', '⬆️', '⬇️', '↗️', '↘️', '↙️', '↖️', '↕️', '↔️', '↪️', '↩️', '⤴️', '⤵️', '🔀', '🔁', '🔂', '🔄', '🔃', '🎵', '🎶', '➕', '➖', '➗', '✖️', '♾', '💲', '💱', '™️', '©️', '®️', '👁‍🗨', '🔚', '🔙', 'ON!', 'TOP', 'SOON', '🔜', '🆕', '🆙', '🆗', '🆒', '🆓'] }
    };

    let lastFocusedElement = null;

    function initEmojiPicker() {
        const grid = document.getElementById('emoji-grid');
        grid.innerHTML = '';

        for (const cat in EMOJI_DATA) {
            const category = EMOJI_DATA[cat];

            // Category Header in Grid
            const header = document.createElement('div');
            header.id = 'cat-anchor-' + cat;
            header.className = 'col-span-6 text-[9px] font-black text-p-muted uppercase tracking-widest mt-4 mb-2 border-b border-white/5 pb-1';
            header.innerText = category.label;
            grid.appendChild(header);

            // Emojis
            category.emojis.forEach(emoji => {
                const btn = document.createElement('button');
                btn.className = 'text-xl p-1 hover:bg-white/10 rounded-lg transition-all transform hover:scale-125';
                btn.innerText = emoji;
                btn.onclick = () => insertEmoji(emoji);
                btn.onmouseenter = () => {
                    document.getElementById('emoji-preview').innerText = `Emoji: ${emoji}`;
                };
                grid.appendChild(btn);
            });
        }

        // Global click listener to detect last focused input
        document.addEventListener('focusin', (e) => {
            if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') {
                lastFocusedElement = e.target;
            }
        });
    }

    function toggleEmojiPicker() {
        const picker = document.getElementById('emoji-picker-container');
        const isHidden = picker.classList.contains('hidden');

        if (isHidden) {
            picker.classList.remove('hidden');
            document.getElementById('emoji-search').focus();
        } else {
            picker.classList.add('hidden');
        }
    }

    function scrollToEmojiCategory(cat) {
        const el = document.getElementById('cat-anchor-' + cat);
        if (el) {
            el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }

    function filterEmojis(query) {
        const grid = document.getElementById('emoji-grid');
        const btns = grid.getElementsByTagName('button');
        const headers = grid.getElementsByTagName('div');

        if (!query) {
            for (let b of btns) b.style.display = 'block';
            for (let h of headers) h.style.display = 'block';
            return;
        }

        // In a real scenario we'd need names, for now we just show all if searching
        // but hide category headers to make it a flat list
        for (let h of headers) h.style.display = 'none';
        // (Simple filtering logic would go here if we had metadata)
    }

    function insertEmoji(emoji) {
        if (!lastFocusedElement) {
            // If no focus, try to find the first visible input in a form
            lastFocusedElement = document.querySelector('input:not([type="hidden"]), textarea');
        }

        if (lastFocusedElement) {
            const start = lastFocusedElement.selectionStart;
            const end = lastFocusedElement.selectionEnd;
            const text = lastFocusedElement.value;
            const before = text.substring(0, start);
            const after = text.substring(end, text.length);

            lastFocusedElement.value = before + emoji + after;
            lastFocusedElement.selectionStart = lastFocusedElement.selectionEnd = start + emoji.length;
            lastFocusedElement.focus();

            // Trigger input event for frameworks/listeners
            lastFocusedElement.dispatchEvent(new Event('input', { bubbles: true }));
        }
    }

    // Shortcut Ctrl+E
    document.addEventListener('keydown', (e) => {
        if (e.ctrlKey && e.key === 'e') {
            e.preventDefault();
            toggleEmojiPicker();
        }
    });

    document.addEventListener('DOMContentLoaded', initEmojiPicker);
</script>

<style>
    .no-scrollbar::-webkit-scrollbar {
        display: none;
    }

    .no-scrollbar {
        -ms-overflow-style: none;
        scrollbar-width: none;
    }

    .custom-scrollbar::-webkit-scrollbar {
        width: 4px;
    }

    .custom-scrollbar::-webkit-scrollbar-track {
        background: transparent;
    }

    .custom-scrollbar::-webkit-scrollbar-thumb {
        background: rgba(255, 255, 255, 0.1);
        border-radius: 10px;
    }

    .custom-scrollbar::-webkit-scrollbar-thumb:hover {
        background: rgba(var(--primary-rgb), 0.5);
    }
</style>